### ISSUE TITLE
Fix car accelerating when brake is pressed

### ISSUE THREAD

**Issue by SeanGolez** [jeffreyHoelzel/cs386-a2.1#2]
Fix bug where car accelerates when user wishes to brake.

**Comment by jeffreyHoelzel** [comment]
@SeanGolez can we just have the engineers swap the brake and accelerator pedals and call it a day?

**Comment by jeffreyHoelzel** [comment]
actually just fixed it, simple syntax error in the driver.

**Comment by jeffreyHoelzel** [comment]
actually just fixed it, simple syntax error with the driver program fileset.
